/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ModalDialog: typeof import('./src/components/ModalDialog.vue')['default']
    PaymentList: typeof import('./src/components/PaymentList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Vloader: typeof import('./src/components/Vloader.vue')['default']
  }
}
